#!/bin/sh

ROOT_PATH=$(dirname "$(readlink -f "$0")")"/"

echo "Setting up server in" $ROOT_PATH;

echo "";

if command -v ldc2 >/dev/null 2>&1; then
    DC="ldc2"
elif command -v ldc >/dev/null 2>&1; then
    DC="ldc"
else
    echo "Error: ldc2 or ldc not found."
    exit 1
fi

$DC --version | head -n 2

echo "module root_conf; enum root_path = \"${ROOT_PATH}\";" > ./libs/root_conf.d
echo "";

CD="\033[0m" #Color Default
CB="\033[34m" #Color Blue

echo $CB"Compiling libs/iod.d"$CD
$DC -O -release -od=./libs -of=./libs/iod.dc ./libs/iod.d

echo $CB"Compiling libs/process_image.d"$CD
$DC -O -release -od=./libs -of=./libs/process_image.dc ./libs/process_image.d
