#!/bin/sh

ROOT_PATH=$(dirname "$(readlink -f "$0")")"/"

CD="\033[0m" #Color Default
CB="\033[34m" #Color Blue
CY="\033[33m" #Color Yellow
CR="\033[31m"

echo "Building Server Components in"$CB $ROOT_PATH $CD;
echo "Please only build from the directory, the code is in.";

echo "";

echo "Writing local variables to configuration";

echo """
module libs.root_conf;
enum root_path = \"${ROOT_PATH}\";

enum ffmpeg_path = \"$(which ffmpeg)\";
enum ffprobe_path = \"$(which ffprobe)\";

enum nice_path = \"$(which nice)\";
""" > ./libs/root_conf.d

echo "";

dub build --config=libs;

echo "";

dub build --config=install_helper;

echo "";